#!/usr/bin/env python3
"""
get_fonts.py: Self-host Google Fonts woff2 subsets as local fallbacks.

WHY: Google Fonts intermittently serves stale css2 pointing to purged
gstatic files (the vietnamese subset 404s). This downloads the CURRENT
woff2 files into assets/fonts/ and regenerates assets/css/v2/fonts.css
with Google's exact unicode-ranges, so 'Outfit Local' / 'Plus Jakarta
Sans Local' / 'JetBrains Mono Local' act as glyph-level fallbacks that
match the Google faces exactly.

RUN (Windows, from the site root):
    python _audit/get_fonts.py

No external packages needed (stdlib urllib only).
Output: assets/fonts/*.woff2 (~1 MB) + assets/css/v2/fonts.css (rewritten).
"""

import os
import re
import sys
import urllib.request

CSS2_URL = ("https://fonts.googleapis.com/css2?"
            "family=Outfit:wght@400;500;600;700"
            "&family=Plus+Jakarta+Sans:wght@400;500;600;700"
            "&family=JetBrains+Mono:wght@500;600;700"
            "&family=Noto+Sans+SC:wght@400;500;600;700"
            "&display=swap")

UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT_DIR = os.path.join(ROOT, "assets", "fonts")
CSS_PATH = os.path.join(ROOT, "assets", "css", "v2", "fonts.css")

# family slug -> allowed weights
TARGETS = {
    "outfit": {400, 500, 600, 700},
    "plus jakarta sans": {400, 500, 600, 700},
    "jetbrains mono": {500, 600, 700},
    # Noto Sans SC intentionally skipped: CJK fallback (PingFang/YaHei)
    # already exists in --ph-font-cjk and CJK woff2 files are huge.
}

SLUG = {
    "outfit": "outfit",
    "plus jakarta sans": "plus-jakarta-sans",
    "jetbrains mono": "jetbrains-mono",
}

HEADER = """/* ═══════════════════════════════════════════════════════════════════
   fonts.css: Local font fallbacks (self-hosted woff2)
   ═══════════════════════════════════════════════════════════════════
   Generated by _audit/get_fonts.py: do not hand-edit.
   Loaded AFTER the Google Fonts stylesheet on every page. Google
   families stay primary; the '… Local' families take over
   glyph-by-glyph only when Google Fonts fails or a subset 404s.
   ═══════════════════════════════════════════════════════════════════ */

"""


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read()


def main():
    print("[1/4] Fetching css2 stylesheet from Google Fonts ...")
    try:
        css = fetch(CSS2_URL).decode("utf-8")
    except Exception as exc:
        print(f"  FAILED: {exc}")
        print("  Check internet connection and retry. Aborting.")
        return 1
    print(f"  OK ({len(css)} bytes)")

    faces = re.findall(r"@font-face\s*{([^}]*)}", css, re.S)
    print(f"[2/4] Found {len(faces)} @font-face blocks.")

    os.makedirs(FONT_DIR, exist_ok=True)
    downloaded = []
    local_faces = []
    for idx, block in enumerate(faces, 1):
        fam = re.search(r"font-family:\s*'([^']+)'", block)
        wt = re.search(r"font-weight:\s*(\d+)", block)
        ur = re.search(r"unicode-range:\s*([^;]+);", block)
        src = re.search(r"src:\s*url\((https://[^)]+\.woff2)\)", block)
        if not (fam and wt and ur and src):
            print(f"  ! block {idx}: parse skip (missing field)")
            continue
        family = fam.group(1).lower()
        weight = int(wt.group(1))
        url = src.group(1)
        unicode_range = " ".join(ur.group(1).split())
        if family not in TARGETS or weight not in TARGETS[family]:
            continue
        if "1EA0-1EF9" in unicode_range:
            subset = "vietnamese"
        elif "0000-00FF" in unicode_range:
            subset = "latin"
        else:
            continue  # skip latin-ext/cyrillic etc.
        fname = f"{SLUG[family]}-{weight}-{subset}.woff2"
        fpath = os.path.join(FONT_DIR, fname)
        try:
            data = fetch(url)
        except Exception as exc:
            print(f"  ! {fname}: download failed ({exc})")
            continue
        if len(data) < 100 or data[:4] != b"wOF2":
            print(f"  ! {fname}: not a valid woff2 ({len(data)} bytes)")
            continue
        with open(fpath, "wb") as fh:
            fh.write(data)
        downloaded.append(fname)
        local_faces.append(
            "@font-face { font-family: '%s Local'; font-style: normal; "
            "font-weight: %d; font-display: swap; src: url('../../fonts/%s') "
            "format('woff2'); unicode-range: %s; }"
            % (fam.group(1), weight, fname, unicode_range)
        )
        print(f"  + {fname} ({len(data)//1024} KB)")

    print(f"[3/4] Downloaded {len(downloaded)} woff2 files "
          f"-> assets/fonts/")

    with open(CSS_PATH, "w", encoding="utf-8") as fh:
        fh.write(HEADER)
        fh.write("\n".join(local_faces))
        fh.write("\n")
    print(f"[4/4] Regenerated {os.path.relpath(CSS_PATH, ROOT)} "
          f"({len(local_faces)} local faces).")

    missing = 19 - len(downloaded)
    if missing > 0:
        print(f"\nNOTE: {missing} expected file(s) missing (Google may "
              f"not serve every subset/weight combo). Fine: the local "
              f"faces that exist will still cover their ranges.")
    print("\nDONE. Reload any page (Ctrl+F5): the fallbacks are active.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
